// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiketsTerminal.Infrastucture.Infrastructure;

namespace TiketsTerminal.Infrastucture.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20221103132803_tickets")]
    partial class tickets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TiketsTerminal.Domain.Models.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_Film")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Poster_Url");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Trailer_Url");

                    b.HasKey("ID");

                    b.ToTable("T_Film", "fbd");
                });

            modelBuilder.Entity("TiketsTerminal.Domain.Models.FilmViewingTime", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_Film_Viewing_Time")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<int>("FK_Film")
                        .HasColumnType("int")
                        .HasColumnName("FK_Film");

                    b.Property<int>("FK_Room")
                        .HasColumnType("int")
                        .HasColumnName("FK_Room");

                    b.HasKey("ID");

                    b.HasIndex("FK_Film");

                    b.HasIndex("FK_Room");

                    b.ToTable("T_Film_Viewing_Time", "fbd");
                });

            modelBuilder.Entity("TiketsTerminal.Domain.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_Film")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("Number");

                    b.Property<int>("SeatsCount")
                        .HasColumnType("int")
                        .HasColumnName("Seats_Count");

                    b.HasKey("ID");

                    b.ToTable("T_Room", "fbd");
                });

            modelBuilder.Entity("TiketsTerminal.Domain.Models.TicketOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_Ticket_Order")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Creation_Date");

                    b.Property<int>("FK_Film_Viewing_Time")
                        .HasColumnType("int")
                        .HasColumnName("FK_Film_Viewing_Time");

                    b.Property<int>("FK_User")
                        .HasColumnType("int")
                        .HasColumnName("FK_User");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_Film_Viewing_Time");

                    b.HasIndex("FK_User");

                    b.ToTable("T_Ticket_Order", "fbd");
                });

            modelBuilder.Entity("TiketsTerminal.Domain.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_User")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<int>("FK_Role")
                        .HasColumnType("int")
                        .HasColumnName("FK_Role");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastVisited")
                        .HasColumnType("datetime2")
                        .HasColumnName("Last_Visited");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.HasKey("ID");

                    b.ToTable("T_User", "fbd");
                });

            modelBuilder.Entity("TiketsTerminal.Domain.Models.FilmViewingTime", b =>
                {
                    b.HasOne("TiketsTerminal.Domain.Models.Film", "Film")
                        .WithMany("FilmViewingTimes")
                        .HasForeignKey("FK_Film")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiketsTerminal.Domain.Models.Room", "Room")
                        .WithMany("FilmViewingTimes")
                        .HasForeignKey("FK_Room")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TiketsTerminal.Domain.Models.TicketOrder", b =>
                {
                    b.HasOne("TiketsTerminal.Domain.Models.FilmViewingTime", "FilmViewingTime")
                        .WithMany("TicketOrders")
                        .HasForeignKey("FK_Film_Viewing_Time")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiketsTerminal.Domain.Models.User", "User")
                        .WithMany("TicketOrders")
                        .HasForeignKey("FK_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmViewingTime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TiketsTerminal.Domain.Models.Film", b =>
                {
                    b.Navigation("FilmViewingTimes");
                });

            modelBuilder.Entity("TiketsTerminal.Domain.Models.FilmViewingTime", b =>
                {
                    b.Navigation("TicketOrders");
                });

            modelBuilder.Entity("TiketsTerminal.Domain.Models.Room", b =>
                {
                    b.Navigation("FilmViewingTimes");
                });

            modelBuilder.Entity("TiketsTerminal.Domain.Models.User", b =>
                {
                    b.Navigation("TicketOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
